# Generated by Django 2.1.1 on 2018-09-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nyc311record',
            old_name='unique_key',
            new_name='external_unique_key',
        ),
    ]
