# Generated by Django 2.1.1 on 2018-09-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180925_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('chair', models.TextField(null=True)),
                ('district_manager', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('phone_number', models.TextField(null=True)),
                ('email_address', models.TextField(null=True)),
                ('website', models.TextField(null=True)),
                ('board_meeting', models.TextField(null=True)),
                ('cabinet_meeting', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
