# Generated by Django 2.1.1 on 2018-09-25 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_communityboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='nyc311record',
            name='community_board_relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.CommunityBoard'),
        ),
    ]
