# Generated by Django 2.1.1 on 2018-09-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180925_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityboard',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
