# Generated by Django 2.1.1 on 2018-09-25 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_budgetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrequest',
            name='community_board_relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.CommunityBoard'),
        ),
    ]
