# Generated by Django 2.1.1 on 2018-09-25 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180925_2221'),
        ('home', '0008_budgetrequest_community_board_relation'),
    ]

    operations = [
    ]
