# Generated by Django 2.1.1 on 2018-09-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_merge_20180925_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrequest',
            name='request',
            field=models.TextField(),
        ),
    ]
